apiVersion: v1
kind: Secret
metadata:
  name: rhdh-token
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    kubernetes.io/service-account.name: default
type: kubernetes.io/service-account-token