apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ${{values.componentId}}-postgresql
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/component: ${{values.componentId}}-postgresql
    app.kubernetes.io/instance: ${{values.componentId}}-postgresql
    app.kubernetes.io/part-of: ${{values.componentId}}
    backstage.io/kubernetes-id: ${{values.componentId}}
  name: postgresql
type: Opaque
stringData:
  database-name: quarkusdb
  database-password: quarkus
  database-user: quarkus
  database-url: jdbc:postgresql://postgresql:5432/quarkusdb