apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{values.componentId}}-postgresql
    app.openshift.io/runtime: postgresql
    app.kubernetes.io/component: ${{values.componentId}}-postgresql
    app.kubernetes.io/instance: ${{values.componentId}}-postgresql
    app.kubernetes.io/part-of: ${{values.componentId}}
    backstage.io/kubernetes-id: ${{values.componentId}}
  name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    name: postgresql
  sessionAffinity: None
  type: ClusterIP

