apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.componentId}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    backstage.io/source-location: url:https://${{values.host}}/${{values.repo_owner}}/${{values.repo_name}}
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: ${{values.componentId}}
    backstage.io/kubernetes-id: ${{values.componentId}}
    janus-idp.io/tekton: ${{values.componentId}}
  tags:
    - java
    - quarkus
  links:
    - url: https://www.redhat.com/en/blog/channel/hybrid-cloud-infrastructure
      title: Red Hat Blog
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
