site_name: ${{ values.repo_name }}
site_description: ${{ values.description }}
repo_url: https://${{values.host}}/${{values.repo_owner}}/${{values.repo_name}}
#edit_uri: _edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - ${{ values.repo_name }} Documentation: index.md