kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Super Duper IDP
      baseUrl: https://backstage-developer-hub-rhdh.apps-crc.testing

    integrations:
      gitea:
        - host: gitea-scm.apps-crc.testing
          username: ${GITEA_USERNAME}
          password: ${GITEA_PASSWORD}

    catalog:
        rules:
          - allow: [Component, System, Group, Resource, Location, Template, API]
        locations:
          - type: url
            target: https://gitea-scm.apps-crc.testing/developer/rhdh-build-an-idp/src/branch/main/gpts/demo-templates.yaml
            
    backend:
      auth:
        keys:
          - secret: ${BACKEND_AUTH_SECRET}
      baseUrl: https://backstage-developer-hub-rhdh.apps-crc.testing
      cors:
        origin: https://backstage-developer-hub-rhdh.apps-crc.testing

    enabled:
      gitea: true