apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    backstage.io/kubernetes-id: ${{values.componentId}}
  name: build-app
  namespace: ${{values.namespace}}-cicd
spec:
  params:
    - name: git-repo-url
      type: string
      description: Source repository url.
      default: https://gitea-scm.apps-crc.testing/redhat/${{values.componentId}}.git
    - name: image-dest-url                                                                        
      type: string                                                                                                                             
      description: External registry location to copy image to
      default: image-registry.openshift-image-registry.svc:5000/${{values.namespace}}-cicd/${{values.componentId}}
  tasks:
    - name: git-clone
      params:
        - name: url
          value: '$(params.git-repo-url)'
        - name: revision
          value: ''
        - name: sslVerify
          value: 'false'
        - name: deleteExisting
          value: 'true'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: maven
      params:
        - name: MAVEN_IMAGE
          value: 'registry.redhat.io/ubi8/openjdk-17:latest'
        - name: GOALS
          value:
            - clean
            - package
        - name: CONTEXT_DIR
          value: .
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: workspace
        - name: maven-settings
          workspace: workspace
    - name: buildah
      params:
        - name: IMAGE
          value: '$(params.image-dest-url):latest'
        - name: BUILDER_IMAGE
          value: 'registry.redhat.io/rhel8/buildah:latest'
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Containerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
      runAfter:
        - maven
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
    - name: skopeo-copy
      params:
        - name: srcImageURL
          value: 'docker://$(params.image-dest-url):latest'
        - name: destImageURL
          value: 'docker://$(params.image-dest-url):dev'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      runAfter:
        - buildah
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: workspace
    - name: skopeo-copy-qa
      params:
        - name: srcImageURL
          value: 'docker://$(params.image-dest-url):latest'
        - name: destImageURL
          value: 'docker://$(params.image-dest-url):qa'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      runAfter:
        - buildah
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: workspace
  workspaces:
    - name: workspace
