apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: ${{values.componentId}} CICD
    openshift.io/display-name: ${{values.componentId}} CICD
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    backstage.io/kubernetes-id: ${{values.componentId}}
  name: ${{values.namespace}}-cicd