apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: workspace
  namespace: ${{values.namespace}}-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi