apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: pipeline
  namespace: ${{values.namespace}}-cicd
secrets:
  - name: gitea-creds
