kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: '@cmoulliard/plugin-scaffolder-backend-module-gitea'
        disabled: false
        integrity: sha512-bok0YyWLcjkG+/vw29z6dwFn/DsO76ohZnAa4vEqhUhA6RnA3qKTyTFCdYMxl5iajJT6RRDmYjZNnRXBRmHLBQ==
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
        disabled: false
      # - package: '@backstage/plugin-scaffolder-backend-module-gitea'
      #   disabled: false
      #   integrity: sha512-S8tOJfPjCR5ERn/CkV+uDRWaW1jH2dl3eKtzXt8EO8WAmG70H0kmnelEeWN7F+9Z5UOkY4ORA8wfg53OEyCtIQ==