kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-config-rbac-policy
  namespace: rhdh
immutable: false
data:
  rbac-policy.csv: |-
    p, role:default/admins, catalog-entity, read, allow
    p, role:default/admins, catalog.entity.create, create, allow
    p, role:default/admins, catalog.entity.refresh, update, allow
    p, role:default/admins, catalog.location.create, create, deny
    p, role:default/admins, catalog.location.read, read, deny
    g, user:default/c383241b-4321-4ffb-8f78-08f8787d5746, role:default/admins