namespace: ${{values.namespace}}-qa

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ${{values.componentId}}
    newName: image-registry.openshift-image-registry.svc:5000/${{values.namespace}}-cicd/${{values.componentId}}
    newTag: qa