apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ${{values.componentId}} QA
    openshift.io/display-name: ${{values.componentId}} QA
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    backstage.io/kubernetes-id: ${{values.componentId}}
  name: ${{values.namespace}}-qa