apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  labels:
    backstage.io/kubernetes-id: ${{values.componentId}}
  generateName: initial-build-
spec:
  pipelineRef:
    name: build-${{values.componentId}}-app
    namespace: ${{values.namespace}}-cicd
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
