apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${{values.component_id}}
    app.kubernetes.io/component: ${{values.component_id}}
    app.kubernetes.io/instance: ${{values.component_id}}
    app.kubernetes.io/part-of: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
  name: ${{values.namespace}}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ${{values.component_id}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${{values.component_id}}
        deploymentconfig: ${{values.component_id}}
        backstage.io/kubernetes-id: ${{values.component_id}}
    spec:
      containers:
      - image: ${{values.component_id}}:latest
        imagePullPolicy: Always
        name: ${{values.component_id}}
        resources:
          limits:
            memory: 512Mi
            cpu: '1'
          requests:
            memory: 512Mi
            cpu: 250m
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30