apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ${{values.component_id}} DEV
    openshift.io/display-name: ${{values.component_id}} DEV
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    backstage.io/kubernetes-id: ${{values.component_id}}
  name: ${{values.namespace }}-dev