apiVersion: v1
kind: Secret
metadata:
  name: gitea-https-creds
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  #url: https://gitea-scm.apps-crc.testing
  url: https://gitea-scm.apps.cluster-w8rdk.w8rdk.sandbox848.opentlc.com
  type: git
  password: openshift
  username: developer
