apiVersion: v1
kind: Secret
metadata:
  name: gitea-https-creds
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: https://gitea-scm.apps-crc.testing
  type: git
  password: openshift
  username: developer