apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-extended-clusterrole
rules:
  - apiGroups:
    - ""
    resources:
      - serviceaccounts
      - resourcequotas
      - limitranges
    verbs:
      - '*'
  - apiGroups:
    - "operator.tekton.dev"
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
    - "tekton.dev"
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
    - "route.openshift.io"
    resources:
      - '*'
    verbs:
      - '*'