apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-extended-clusterrole
rules:
  - apiGroups:
    - "rhdh.redhat.com"
    resources:
      - '*'
    verbs:
      - '*'
